### ISSUE TITLE
Infinite Recursion while Caching FeatureExtractionResult (Testing Botan)

### ISSUE THREAD

**Issue by FAlbertDev** [tls-attacker/TLS-Anvil#12]
Hi Marcel,

I'm currently working on a project where we extend and maintain the Botan library. For that, I want
to integrate TLS Anvil into Botan's CI. While experimenting with Botan and TLS-Anvil, a bug occurred.

## Description of the problem
The problem occurs after the TLS-Scanner scan is completed. It happens while the FeatureExtractionResult
is cached (saveToCache). An infinite recursion occurs while writing the objects to the .json file.

```LOG
# <date>_testsuite.log

07-24-2023_07:30:19 [Thread-0] DEBUG: Main.lambda$main$0(Main.java:30) - RAM: 49/132
07-24-2023_07:30:19 [main] INFO : Main.main(Main.java:50) - Limiting test to those of package both.tls12.rfc5246.Fragmentation.sendZeroLengthApplicationRecord
07-24-2023_07:30:19 [main] WARN : TestRunner.startTcpDump(TestRunner.java:337) - Tcpdump will capture on all interfaces. Use -networkInterface to reduce amount of collected data.
07-24-2023_07:30:21 [Thread-0] DEBUG: Main.lambda$main$0(Main.java:30) - RAM: 51/132
07-24-2023_07:30:21 [main] INFO : TestRunner.prepareTestExecution(TestRunner.java:381) - Starting preparation phase
07-24-2023_07:30:22 [main] INFO : TestRunner.serverTestPreparation(TestRunner.java:215) - Server available, starting TLS-Scanner
07-24-2023_07:30:23 [Thread-0] DEBUG: Main.lambda$main$0(Main.java:30) - RAM: 65/132
...
07-24-2023_07:31:27 [Thread-0] DEBUG: Main.lambda$main$0(Main.java:30) - RAM: 67/409
07-24-2023_07:31:29 [main] ERROR: Main.main(Main.java:58) - Something went wrong
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.util.LinkedList[0]->de.rub.nds.tlsattacker.core.http.header.HostHeader["allModifiableVariableHolders"]->java.util.LinkedList[0]->de.rub.nds.tlsattacker.core.http.header.HostHeader["allModifiableVariableHolders"]->java.util.LinkedList[0]->de.rub.nds.tlsattacker.core.http.header.HostHeader["allModifiableVariableHolders"]->java.util.LinkedList[0]->de.rub.nds.tlsattacker.core.http.header.HostHeader["allModifiableVariableHolders"]->java.util.LinkedList[0]->de.rub.nds.tlsattacker.core.http.header.HostHeader["allModifiableVariableHolders"]->java.util.LinkedList[0]->de.rub.nds.tlsattacker.core.http.header.HostHeader["allModifiableVariableHolders"]->java.util.LinkedList[0]->

# ... and so on
```

If I remove the `saveToCache` code manually, it works (of course, without the cache output).
I don't know how fasterxml parses the objects, but it seems there is somehow a recursive reading in the modifiableVariable of _Host_.

## Additional Information
- TLS-Anvil version: v1.2.1
- Issue occurred using TLS-Anvil while testing the following TLS server/client:
```Shell
# === Current botan master ===
# Built with:
./configure.py --compiler-cache=ccache --build-targets=static,cli --without-documentation && make -j8
# Server started with:
./botan tls_server cert.pem key.pem --port=4433
```

- TLS Anvil built and executed via:
```Shell
# Built and executed with Docker:
./build.sh
docker run --network="host" --rm -it -v <path>/TLS-Anvil:/output tlsanvil \
    -strength 1 \
    -parallelHandshakes 1 \
    server \
    -connect 127.0.0.1:4433
```

- Does not occur with openssl's s_server. The value "HTTPS_HEADER" seems to contain no such values
for openssl.

- Attached are the (broken) cached site report (127.0.0.1:4433.json) and the three log files:
[127.0.0.14433.json.txt](https://github.com/tls-attacker/TLS-Anvil/files/12144620/127.0.0.1.4433.json.txt)
[default_07-24-2023_07-30-19_tlsattacker.log](https://github.com/tls-attacker/TLS-Anvil/files/12144633/default_07-24-2023_07-30-19_tlsattacker.log)
[default_07-24-2023_07-30-19_testsuite.log](https://github.com/tls-attacker/TLS-Anvil/files/12144634/default_07-24-2023_07-30-19_testsuite.log)
[default_07-24-2023_07-30-19_testsuite_warn.log](https://github.com/tls-attacker/TLS-Anvil/files/12144635/default_07-24-2023_07-30-19_testsuite_warn.log)

- Greetings to the NDS chair :)

**Comment by mmaehren** [comment]
Hey,
sorry I missed the notification. Thank you for the report. The issue does not appear for OpenSSL because s_server does not respond to HTTP requests by default. When adding -www to the command line, the same issue occurrs. Since we are currently in the process of refactoring the report structure of the scanner, I only pushed a workaround that removes the test result (its not required for TLS-Anvil anyway).
If you have feedback regarding implementing TLS-Anvil in a CI pipeline, feel free to send it to us via email or in a GitHub issue.

**Comment by FAlbertDev** [comment]
Great! Thank you!
